---
- name: Create ELB for Nagios Web Front-end
  hosts: localhost
  gather_facts: False


  tasks:

    - name: create auto classic elb for http
      amazon.aws.elb_classic_lb:
        state: present
        name: 'NAG-Web-Front-ELB'
        security_group_ids: "{{ sg_ids}}"
        subnets: "{{ subnet_ids }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        stickiness:
          type: loadbalancer
          enabled: true
          expiration: 300

