###> This is the second file. 
###> Does not recreate nginx, only modifies it.

---
services:
  web:
    build: ./
    container_name: nginxphp_1
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - /var/docker/www/html/:/var/www/html/

  php:
    image: php:8.1-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - /var/docker/www/html:/var/www/html

