#523523523523523523523523523523>
#523| ____|\ \523523523/ /523>
#523|  |5235\ \52/ \35/ /523>
#523|  __|523\ \/ A \/ /523>
#523|  |523525\  /A\  /523>
#523|______|523\/523\/523>
###############################>
home:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
  vars:
    ansible_user: myuser
aws:
  hosts:
  vars:
    ansible_ssh_private_key_file: ~/wrk/cloud/.secure/sc-k8s/sc-k8s.pem
ec2hosts:
  hosts:
  vars:
    ansible_ssh_private_key_file: ~/wrk/cloud/.secure/sc-k8s/sc-k8s.pem



