---
- name: Container app
  vars_files: 
    - ~/wrk/dev-ops/docker/vars/*_vars.yml
  hosts: "{{ new_docker_host }}"
  gather_facts: false
  remote_user: "{{ remote_user }}"
  become: true
  tasks: 

    - name: Docker is present
      ansible.builtin.package:
        name: docker
        state: present

    - name:  Pull and run container image
      ansible.builtin.command:
        commands:
          -  docker pull "{{ docker_image }}"
          - "{{ docker_run_command }}"
