---
- name: Create Launch template
  hosts: localhost
  gather_facts: False

  tasks:

    - name: create launch template
      amazon.aws.ec2_launch_template:
        name: 'launch-template-nag-asg'
        zones: [ 'us-west-2c' ]
          BlockDeviceMappings: 
            - Ebs:
              VolumeSize: 22
                VolumeType: gp2
                DeleteOnTermination: true
                Encrypted: true
                DeviceName: /data0
            CreditSpecification: 
              cpu_credits: Unlimited
              monitoring: 
                enabled: true
            image_id: ami-09bc618489fd6730f 
            instance_type: t2.micro
            key_pairs: sc-k8s
            load_balancers: ['NAG-Web-Front-ELB']
            SecurityGroupIds: 
              - sg-0d4f9d029c393def9
              - sg-0c18d8d383c8a4184
