---
- name: Create Subnet
  hosts: localhost
  gather_facts: False


  tasks:

    - name: Create subnet for database servers
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id:  
        cidr: 10.0.1.16/28
        tags:
          Name: Database Subnet
      register: database_subnet

