apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: tigera-operator
  labels:
    name:
data:
  ETCD_ENDPOINTS: 'https://127.0.0.1:2379,https://10.1.200.50:2379'       # <set to the key 'etcd_endpoints' of config map 'calico-config'>  Optional: false
  ETCD_CA_CERT_FILE: '/etc/kubernetes/pki/etcd/ca.crt'    # <set to the key 'etcd_ca' of config map 'calico-config'>         Optional: false
  ETCD_KEY_FILE: '/etc/kubernetes/pki/etcd/server.key'        # <set to the key 'etcd_key' of config map 'calico-config'>        Optional: false
  ETCD_CERT_FILE: '/etc/kubernetes/pki/etcd/server.crt'       # <set to the key 'etcd_cert' of config map 'calico-config'>       Optional: false
