---

- hosts: k8scp
  gather_facts: false
  tasks:
    - name: Start kubelet
      ansible.builtin.shell: |
        sudo systemctl enable kubelet
        sudo systemctl start kubelet

    - name: Initialize k8s cluster
      ansible.builtin.shell: | 
        sudo kubeadm init --pod-network-cidr=10.96.0.0/16

    - name: Create .kube directory
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Create kube user kubeconfig file from admin.conf
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/eric_richardwalts_com/.kube/config
        remote_src: yes

    - name: Install CNI plugin Tigera Operator Calico
      ansible.builtin.shell: |
        kubectl apply -f gs://rewbin/rewbin_tigera-operator.yaml
        
    - name: Create join token for worker nodes
      ansible.builtin.shell: |
        sudo kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
