---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../vars/current_play_vars.yml
  tasks:
    - name: New EC2 Instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        key_name: "{{ ew_ssh_key }}"
        vpc_subnet_id: "{{ ew_vpc_subnet }}"
        instance_type: t2.medium
        security_groups: "{{ ew_sg }}" 
        network:
          assign_public_ip: true
        image_id: "{{ ew_ami_id }}"
        tags:
          environment: "{{ ew_env }}"
      loop:
        - k8s-cp
        - k8s-wn1
        - k8s-wn2
      register: ec2

